project_id = "bcsqrfucckfkouskqauz"

[functions.score-idea]
verify_jwt = false

[functions.validate-status-change]
verify_jwt = true

[functions.autofill-idea]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.suggest-name]
verify_jwt = false

[functions.draft-pitch]
verify_jwt = false

[functions.generate-idea]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false
